services:
  warp-proxy:
    image: ghcr.io/clockclock1/warp-proxy-docker:latest
    container_name: warp-proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      WARP_MODE: "d"
      WARP_SCRIPT_SOURCE: "local"
      ENABLE_HTTP_PROXY: "true"
      ENABLE_SOCKS5_PROXY: "true"
      HTTP_PROXY_PORT: "8080"
      SOCKS5_PROXY_PORT: "1080"
    volumes:
      - ./data:/var/lib/warp
    ports:
      - "8080:8080"
      - "1080:1080"
